### ISSUE TITLE
Pre-trained model link

### ISSUE THREAD

**Issue by B0RJA** [manideep2510/eye-in-the-sky#14]
The pre-trained model link seems broken:

https://drive.google.com/file/d/1U21Bwchcm96-Nz1SVEo0IvSoPyqqA7gm/view?usp=sharing

Any chance you could upload it again?

Thank you for sharing your work!

**Comment by charleygros** [comment]
Hi there,

I am having the same issue as @BORJA.
Could you please help us?

Many thanks in advance

**Comment by mkr1399** [comment]
Hi there,

I am having the same issue as BORJA.
Could you please help us?
please

**Comment by DalalAlmutawa** [comment]
Hi there,

I am having the same issue as BORJA.
Could you please help us?
please

**Comment by MaksymTymkovych** [comment]
Hi there,

I am having the same issue as all user in that thread.
Could you please help us?

**Comment by levrex** [comment]
Hiya, I have the same problem..

**Comment by cybr17crwlr** [comment]
Hello all,
Sorry but any development for this project has stopped, including any files hosted outside Github. We are sorry for the issue caused, but you can surely use our training technique and are welcome to train a model of your own and put it in the repo via a pull request.

**Comment by kushagra97pal** [comment]
Did anyone trained a new model?
