### ISSUE TITLE
Issue with pretrained weight file model_onehot.h5

### ISSUE THREAD

**Issue by faroo014** [manideep2510/eye-in-the-sky#3]
I am trying to use pretrained weight file model_onehot.h5. I changed the file name at all relevant places in test_unet.py. However, when we load the weight file, it gives following error:

ValueError: Dimension 0 in both shapes must be equal, but are 1 and 9. Shapes are [1,1,16,3] and [9,16,1,1]. for 'Assign_82' (op: 'Assign') with input shapes: [1,1,16,3], [9,16,1,1].

Seems like when loading model.load_weights(weights_file), there is some inconsistency for dimensions.

**Comment by fadishaar84** [comment]
I'm facing the same error, did you manage to solve it?

**Comment by faroo014** [comment]
No, the issue remains unresolved.

**Comment by manideep2510** [comment]
Sorry for the delay.
The code worked fine for me when I last tested it. I will check it again and fix the issue.

**Comment by manideep2510** [comment]
I have solved the issue, the issue we in [unet.py](https://github.com/manideep2510/eye-in-the-sky/blob/master/unet.py) file. 
In line 80, the number of output channels should be 9, not 3.
So changed 
```python 
conv10 = Conv2D(3, 1, activation = 'softmax')(conv9)
``` 
to 
```python
conv10 = Conv2D(9, 1, activation = 'softmax')(conv9)
```
The code should work fine now.
