### ISSUE TITLE
requirements.txt file has incorrect structure

### ISSUE THREAD

**Issue by 41WhiteElephants** [manideep2510/eye-in-the-sky#4]
Hi, could you please fix structure of the requirements.txt file that anybody can use pip install -r requirements.txt command? Also, you didn't mention any info about the versions of libraries you used.

**Comment by manideep2510** [comment]
Fixed the structure of [`requirements.txt`](https://github.com/manideep2510/eye-in-the-sky/blob/master/requirements.txt). Now you can use `pip install -r requirements.txt` command to install the dependencies.
