### ISSUE TITLE
NameError: name 'iou' is not defined in unet.py

### ISSUE THREAD

**Issue by 41WhiteElephants** [manideep2510/eye-in-the-sky#5]
Hi, It seems like variable/function 'iou' is missing in unet.py

My stack trace: 
File "/macierz/home/s174520/eye-in-the-sky/unet.py", line 84, in UNet
    model.compile(optimizer = Adam(lr = 0.000001), loss = 'categorical_crossentropy', metrics = ['accuracy', iou])
NameError: name 'iou' is not defined

Edit:
I checked commit history. I think you have added iou function to test_unet.py file istead of unet.py and you're not passing it to UNet model.

**Comment by manideep2510** [comment]
I have created a new file named [iou.py](iou.py) with the IOU function and imported it in [unet.py](unet.py). This should resolve the error.
