### ISSUE TITLE
how to run this code on kaggle kernel??

### ISSUE THREAD

**Issue by prativadas** [manideep2510/eye-in-the-sky#8]
when I was trying to run the code on kaggle kernel it shows import error for libtiff . can you help with this? i tried replacing libtiff with PIL but again some error came.

**Comment by manideep2510** [comment]
I don't think you can run this code on Kaggle because of the python 3 incompatibilities with libtiff library. If you can manage to change the source code of the library on Kaggle or if you can find a different library to read the .tiff images, you can run this code on Kaggle.

**Comment by prativadas** [comment]
By any means do you have any extra information about the dataset? Like which satellite data used to acquire the images, resolution of the images, location of where the images are taken from. thank you for you response.

**Comment by manideep2510** [comment]
No, I don't have any additional information about the dataset. IIT Bombay provided the data to us but didn't say anything about its background.
